// <auto-generated />
namespace BAP.DB.eCommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StagingEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StagingEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280933140_StagingEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
